### ISSUE TITLE
I have issues with multiboxing/multiple accounts

### ISSUE THREAD

**Issue by Limiana** [PunishXIV/AutoRetainer#62]
If you want to use more than one instance of the game at the same time or if you want to use AutoRetainer on different accounts on the same machine, run first instance normally and for any subsequent instances create one bat file for each instance with this text:
```
start "" /d "%USERPROFILE%\AppData\Local\XIVLauncher" "%USERPROFILE%\AppData\Local\XIVLauncher\XIVLauncher.exe" --roamingPath="c:\XivLauncher2"
```
Replace `c:\XivLauncher2` with path to would be second Xivlauncher configuration folder. Each instance/account needs to use it's own bat file and it's own folder (don't forget to actually create these folder).

**Comment by Nicolas-GE** [comment]
what if i want to just use other accounts for things like, playing a band as bard, and disable autoretainer?

**Comment by Kyla772** [comment]
Is there a way we could get a video tutorial for this? My very few braincells is not really understanding of this

**Comment by nowlflr** [comment]
@Kyla772 
> Is there a way we could get a video tutorial for this? My very few braincells is not really understanding of this

Were you able to figure it out? I'm in the same boat and don't understand it at all.

**Comment by Kyla772** [comment]
> @Kyla772
> 
> > Is there a way we could get a video tutorial for this? My very few braincells is not really understanding of this
> 
> Were you able to figure it out? I'm in the same boat and don't understand it at all.

No nothing at all. If you figure it out, feel free to let me know

**Comment by nowlflr** [comment]
> > @Kyla772
> > > Is there a way we could get a video tutorial for this? My very few braincells is not really understanding of this
> > 
> > 
> > Were you able to figure it out? I'm in the same boat and don't understand it at all.
> 
> No nothing at all. If you figure it out, feel free to let me know

I did figure it out with a little help from discord and lot of insight from my wife to put all the pieces together. I’m not at my computer right now but I could help you tomorrow. If you are on Discord, my name is sahweeet… find me there and I can walk you through it.

**Comment by venomin30** [comment]
These are my steps that I prefer, this also allows me to use different shortcuts of XIVLauncher rather than having it as batch (.bat) files.

1. Go to your `%appdata%` folder, you can paste just that in your File Explorer address bar at the top, or you can put it in your **"Run"** command by pressing **Windows Key+R**.
2. Copy your `XIVLauncher` folder, and paste it in the same directory, and rename the new folder with a "2" on the end (e.g. the copied one is called `XIVLauncher2`). You can repeat this and have 3, 4, 5, etc (just make as many as you need). This allows you to skip having to setup XIVLauncher and Dalamud all over again, as this copies all the configurations of Dalamud itself and each Plugins' settings.
3. Next go to `%localAppData%\XIVLauncher`, right click on `XIVLauncher.exe` and create as many shortcuts as you need.
4. Right click on the new shortcut and go to **Properties**.
5. Go to the **Shortcut** tab.
6. In the **Target** field, go right to the end where it ends with XIVLauncher.exe and in this in including the space ` --roamingPath="%appdata%\XIVLauncher2"`.
7. Repeat Steps 4 to 6 with as many shortcuts as you need and only change the ` --roamingPath="%appdata%\XIVLauncher2"` part with the other folder names you created in Step 2.
8. Rename these Shortcuts with whatever you prefer (I just renamed them XIVLauncher2, etc).
![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/ed8a0efc-8127-4fed-9f7e-a1cb97860ad7)
10. Now you can pin these new shortcuts in your Start menu, or Taskbar.
![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/7b1a91f0-085a-454e-a4a2-dbfbab5eebe6)

A few more steps that originally stated, but this allows you to retain all your Dalamud settings across the new profiles, and allows you to have a shortcut as opposed to running XIVLauncher via a .bat file.

**Comment by venomin30** [comment]
@nowlflr @Kyla772 @Flavescent

These are my steps that I prefer, this also allows me to use different shortcuts of XIVLauncher rather than having it as batch (.bat) files.

1. Go to your `%appdata%` folder, you can paste just that in your File Explorer address bar at the top, or you can put it in your **"Run"** command by pressing **Windows Key+R**.
2. Copy your `XIVLauncher` folder, and paste it in the same directory, and rename the new folder with a "2" on the end (e.g. the copied one is called `XIVLauncher2`). You can repeat this and have 3, 4, 5, etc (just make as many as you need). This allows you to skip having to setup XIVLauncher and Dalamud all over again, as this copies all the configurations of Dalamud itself and each Plugins' settings.
3. Next go to `%localAppData%\XIVLauncher`, right click on `XIVLauncher.exe` and create as many shortcuts as you need.
4. Right click on the new shortcut and go to **Properties**.
5. Go to the **Shortcut** tab.
6. In the **Target** field, go right to the end where it ends with XIVLauncher.exe and in this in including the space ` --roamingPath="%appdata%\XIVLauncher2"`.
7. Repeat Steps 4 to 6 with as many shortcuts as you need and only change the ` --roamingPath="%appdata%\XIVLauncher2"` part with the other folder names you created in Step 2.
8. Rename these Shortcuts with whatever you prefer (I just renamed them XIVLauncher2, etc).
![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/ed8a0efc-8127-4fed-9f7e-a1cb97860ad7)
10. Now you can pin these new shortcuts in your Start menu, or Taskbar.
![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/7b1a91f0-085a-454e-a4a2-dbfbab5eebe6)

A few more steps that originally stated, but this allows you to retain all your Dalamud settings across the new profiles, and allows you to have a shortcut as opposed to running XIVLauncher via a .bat file.

**Comment by Flavescent** [comment]
@venomin30, thanks for documenting your method! But this causes additional issues arising from the fact that one now has to manage _n_ separate Dalamud installations and plugin sets. I would much prefer it if AutoRetainer was able to handle separate service accounts natively, much like it already does separate characters on the same account.

**Comment by venomin30** [comment]
@Flavescent oh definitely agreed! My preference is **NOT** having to do this at all, as this is the **only** Plugin that I have that requires this from having multiple accounts.

**Comment by StellaSky17** [comment]
@venomin30 Thanks for your tip. On the other hand, now I'm having trouble opening the game at the start, very often it closes after a few seconds, whether with the normal or the shortcut. After a while it stays fine and doesn't crash any more, but it's annoying to have to try sometimes up to 10 times before I can play with both my accounts. Maybe I've done something wrong?

**Comment by Limiana** [comment]
> @venomin30, thanks for documenting your method! But this causes additional issues arising from the fact that one now has to manage _n_ separate Dalamud installations and plugin sets. I would much prefer it if AutoRetainer was able to handle separate service accounts natively, much like it already does separate characters on the same account.

It can handle separate service accounts, but not separate square enix accounts. There is no way to determine which account you're using when game starts. Even then, if you're only using subs and retainers on a single account, you shouldn't have issues

**Comment by Battler624** [comment]
> [@nowlflr](https://github.com/nowlflr) [@Kyla772](https://github.com/Kyla772) [@Flavescent](https://github.com/Flavescent)
> 
> These are my steps that I prefer, this also allows me to use different shortcuts of XIVLauncher rather than having it as batch (.bat) files.
> 
>     1. Go to your `%appdata%` folder, you can paste just that in your File Explorer address bar at the top, or you can put it in your **"Run"** command by pressing **Windows Key+R**.
> 
>     2. Copy your `XIVLauncher` folder, and paste it in the same directory, and rename the new folder with a "2" on the end (e.g. the copied one is called `XIVLauncher2`). You can repeat this and have 3, 4, 5, etc (just make as many as you need). This allows you to skip having to setup XIVLauncher and Dalamud all over again, as this copies all the configurations of Dalamud itself and each Plugins' settings.
> 
>     3. Next go to `%localAppData%\XIVLauncher`, right click on `XIVLauncher.exe` and create as many shortcuts as you need.
> 
>     4. Right click on the new shortcut and go to **Properties**.
> 
>     5. Go to the **Shortcut** tab.
> 
>     6. In the **Target** field, go right to the end where it ends with XIVLauncher.exe and add this in including the space ` --roamingPath="%appdata%\XIVLauncher2"`.
>        ![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/52b4efea-797c-4193-ad95-cc1217486e69)
> 
>     7. Repeat Steps 4 to 6 with as many shortcuts as you need and only change the ` --roamingPath="%appdata%\XIVLauncher2"` part with the other folder names you created in Step 2.
> 
>     8. Rename these Shortcuts with whatever you prefer (I just renamed them XIVLauncher2, etc).
>        ![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/ed8a0efc-8127-4fed-9f7e-a1cb97860ad7)
> 
>     9. Now you can pin these new shortcuts in your Start menu, or Taskbar.
>        ![image](https://github.com/PunishXIV/AutoRetainer/assets/92248200/7b1a91f0-085a-454e-a4a2-dbfbab5eebe6)
> 
> 
> A few more steps that originally stated, but this allows you to retain all your Dalamud settings across the new profiles, and allows you to have a shortcut as opposed to running XIVLauncher via a .bat file.
> 
> Please note that this **WILL NOT** sync the XIVLauncher/Dalamud settings across the different folders you created with these steps - please choose the main XIVLauncher as your "primary" and you can just copy that folder across again to the new folders you created in Step 2 if you need this functionality.

Sorry for reviving this topic, as it is not an issue related to autoretainer but it is what I came across when searching for a way to differentiate the settings across different accounts.

I am just wondering, what folders would "--roamingpath" affect? Is it literally everything? if that is the case, wouldn't creating symbolic links between everything inside except "pluginconfigs" create an overall easier to manage installation?

**Comment by venomin30** [comment]
> Sorry for reviving this topic, as it is not an issue related to autoretainer but it is what I came across when searching for a way to differentiate the settings across different accounts.
> 
> I am just wondering, what folders would "--roamingpath" affect? Is it literally everything? if that is the case, wouldn't creating symbolic links between everything inside except "pluginconfigs" create an overall easier to manage installation?

@Battler624 No worries, the problem is that you can't have exceptions in Symlinks. It's all or nothing. Which is why we need to have this convoluted solution. Because Autoretainer's config lives as a subfolder of pluginConfig, you can't have exceptions to only that.
